# Generated by Django 5.2 on 2025-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('c', 'completed')], default='p', max_length=50),
        ),
    ]
